name: rownd_flutter_plugin
description: Rownd bindings for Flutter
version: 1.3.4
homepage: https://rownd.com
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.5.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.6.0
  web: '>=0.4.0 <1.0.0'
  js: '>=0.6.0 <1.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
flutter:
  plugin:
    platforms:
      android:
        package: io.rownd.flutter
        pluginClass: RowndFlutterPlugin
      ios:
        pluginClass: RowndFlutterPlugin
