# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub get
        working-directory: ./examples/rownd_about
      #- run: flutter test
      - run: flutter build apk
        working-directory: ./examples/rownd_about
      - run: flutter build appbundle
        working-directory: ./examples/rownd_about

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub get
        working-directory: ./examples/rownd_about
      #- run: flutter test
      - run: flutter build ios --release --no-codesign
        working-directory: ./examples/rownd_about

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub get
        working-directory: ./examples/rownd_about
      #- run: flutter test
      - run: flutter build web
        working-directory: ./examples/rownd_about
